### ISSUE TITLE
Preserve filters on saved image

### ISSUE THREAD

**Issue by 33mhz** [xavierfoucrier/instacam#39]
When I `camera.snap()` or `camera.save()`, and in the demo, the filters' effects are gone from the saved image. Maybe I'm missing the obvious way to preserve the filters on the saved image?

**Comment by xavierfoucrier** [comment]
Hi @33mhz,

Unfortunately, Instacam is using **CSS filters "over" the viewport** to alter the image rendering. As the CSS filters are a browser layout, they are not directly applied to the canvas image, that's why the snap and save methods are not able to capture thoose styles.

However, you can use the [filter property](https://github.com/xavierfoucrier/instacam/blob/master/DOCUMENTATION.md#filter) to create a custom filter that will alter the canvas image: many CSS filters can be easily reproduce with this option like brightness, contrast, saturation, hue, invert, grayscale and sepia.

Instacam is using CSS filters because they are **more faster** than applying a custom filter, especially if the viewport size is wide.

I will update the documentation accordingly. :wink:
