### ISSUE TITLE
iPhone 12 fallback to bad format

### ISSUE THREAD

**Issue by StoyanONLIME** [xavierfoucrier/instacam#62]
We tried to use this library for a web project and discovered that on all iPhone devices there is a fallback with wrong dimensions. Whatever settings we provide for the image format, it is squeezed and presented Landscape instead of Portrait.
Any suggestions would be highly 
![viber_image_2021-08-04_13-49-17-927](https://user-images.githubusercontent.com/88442593/128192666-c9d738be-7a7e-45cf-b315-1fb31e71166f.jpg)
appreciated.

**Comment by xavierfoucrier** [comment]
Hi @StoyanONLIME,

Thanks for opening an issue.
I will take time to investigate on this soonly :wink:

**Comment by xavierfoucrier** [comment]
Hi @StoyanONLIME,

Sorry for the late reply, I am on vacations until monday. Just to let you know that I fixed the docs website: feel free to check again. The issue was related to a fixed ratio applied to the camera viewport.

Big thanks for using the library!

Feel free to star the repo or support it by sponsoring me on Github 😉👍🍻

> As a side note, when you specify a size on initialization, you are "requesting" a size for WebRTC, meaning that the hardware can support the requested size... or not: in most time, WebRTC will try to be as closer as possible to your requested size, but can fallback to another one if the hardware doesn't support it.
